### ISSUE TITLE
org.opencpn.OpenCPN.Plugin.vdr.yaml    should freedesktop be changed?

### ISSUE THREAD

**Issue by rgleason** [rgleason/vdr_pi#17]
```
#
id: org.opencpn.OpenCPN.Plugin.VDR
runtime: org.opencpn.OpenCPN
runtime-version: stable   # official build at flathub
#runtime-version: master   # for nightly builds
sdk: org.freedesktop.Sdk//18.08
```

Should it be changed to  20.04?

This is direct from ShipDriver

**Comment by rgleason** [comment]
It would be very nice to know the answer here
@rasbats
@leamas
@bdbcat

**Comment by rgleason** [comment]
So that config.h.in was the issue with using something more generic like plugin_use_svg which always failed!

The wiring isnt very intuitive here, but I am starting to get it.

**Comment by rgleason** [comment]
So did you fix the op issue?

**Comment by leamas** [comment]
> So did you fix the op issue?

Op issue?
