### ISSUE TITLE
RFE: Ability to stop and back up to and select a new start point.

### ISSUE THREAD

**Issue by rgleason** [rgleason/vdr_pi#23]
Ability to select freely where to start from.
Ability to bracket a section and play it over and over. (Two sliding end stops)
Ability to speed up and slow down.
Ability to step through some how, or easily slow it down by pressing a button.
Small window shows which sentence is being used.

**Comment by sebastien-rosset** [comment]
The following should be done in #39 :

> Ability to select freely where to start from.
> Ability to speed up and slow down.

**Comment by rgleason** [comment]
Then I think that perhaps this can be closed.
