### ISSUE TITLE
1.3.27 has 3 bookworm failures and 2 android failures to build

### ISSUE THREAD

**Issue by rgleason** [rgleason/vdr_pi#31]
https://github.com/rgleason/vdr_pi

**Comment by Rasbats** [comment]
Can this be closed?

**Comment by rgleason** [comment]
Mike, you are welcome to close it. I cannot test for bookworm and only reported something reported by someone else.  So if you wish go ahead and close it.

BTW does this plugin need to be updated to fix this?  If so what is the update?
